#ifndef __mainframe__
#define __mainframe__

/**
@file
Subclass of GUI_MainFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing GUI_MainFrame */
class MainFrame : public GUI_MainFrame
{
protected:
	// Handlers for GUI_MainFrame events.
	void OnStartClick( wxCommandEvent& event );
	void OnCloseClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	MainFrame( wxWindow* parent );
};

#endif // __mainframe__
